language: python
dist: precise

python:
  - "3.5"

cache: pip

addons:
  apt:
    packages:
      - expect-dev  # provides unbuffer utility
      - python-lxml  # because pip installation is slow
      - libxml2-dev
      - libxmlsec1-dev
      - libxslt-dev

env:
  global:
  - VERSION="10.0" TESTS="0" LINT_CHECK="0" TRANSIFEX="0"
  - VERSION="10.0" ODOO_REPO="multidadosti-erp/odoo" LINT_CHECK="0"
  matrix:
  - LINT_CHECK="1"
  - TESTS="1" ODOO_REPO="multidadosti-erp/odoo"
  - TESTS="1" ODOO_REPO="multidadosti-erp/odoo" UNIT_TEST="1"


install:
  - git clone --depth=1 https://github.com/multidadosti-erp/maintainer-quality-tools.git ${HOME}/maintainer-quality-tools
  - export PATH=${HOME}/maintainer-quality-tools/travis:${PATH}
  - travis_install_nightly

script:
  - travis_run_tests

after_success:
  - travis_after_tests_success